spring:
  application:
    name: SpringBatchWithDB

  datasource:
    url: jdbc:mysql://localhost:3306/rojkharido
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false